<?php

namespace Container2Yie2nx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Jh6ql_BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jh6ql.b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jh6ql.b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'valueRepository' => ['privates', 'App\\Repository\\ValueRepository', 'getValueRepositoryService', true],
        ], [
            'valueRepository' => 'App\\Repository\\ValueRepository',
        ]);
    }
}
