<?php

namespace Container2Yie2nx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRedirect404ListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\Redirect404Listener' shared autowired service.
     *
     * @return \App\EventListener\Redirect404Listener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/Redirect404Listener.php';

        return $container->privates['App\\EventListener\\Redirect404Listener'] = new \App\EventListener\Redirect404Listener(($container->services['router'] ?? self::getRouterService($container)));
    }
}
