<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2Yie2nx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2Yie2nx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2Yie2nx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2Yie2nx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2Yie2nx\App_KernelDevDebugContainer([
    'container.build_hash' => '2Yie2nx',
    'container.build_id' => 'e2851bfd',
    'container.build_time' => 1690993314,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2Yie2nx');
