<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_find_range' => [[], ['_controller' => 'App\\Controller\\FindRangeController::index'], [], [['text', '/find_range']], [], [], []],
    'app_value_index' => [['value'], ['_controller' => 'App\\Controller\\ValueController::index'], [], [['variable', '/', '[^/]++', 'value', true], ['text', '/check-value']], [], [], []],
];
